package com.example.newzy.model

class CountriesList {
    companion object {
        val country = listOf(
            Country(name = "Argentina", code = "ar"),
            Country(name = "Austria", code = "at"),
            Country(name = "Australia", code = "au"),
            Country(name = "Belgium", code = "be"),
            Country(name = "Bulgaria", code = "bg"),
            Country(name = "Brazil", code = "br"),
            Country(name = "Canada", code = "ca"),
            Country(name = "China", code = "cn"),
            Country(name = "Colombia", code = "co"),
            Country(name = "Cuba", code = "cu"),
            Country(name = "Czechia", code = "cz"),
            Country(name = "Egypt", code = "eg"),
            Country(name = "France", code = "fr"),
            Country(name = "Germany", code = "de"),
            Country(name = "Greece", code = "gr"),
            Country(name = "Hong Kong", code = "hk"),
            Country(name = "Hungary", code = "hu"),
            Country(name = "Indonesia", code = "id"),
            Country(name = "Ireland", code = "ie"),
            Country(name = "India", code = "in"),
            Country(name = "Italy", code = "it"),
            Country(name = "Japan", code = "jp"),
            Country(name = "Kingdom Of Saudi Arabia", code = "sa"),
            Country(name = "Lithuania", code = "lt"),
            Country(name = "Latvia", code = "lv"),
            Country(name = "Morocco", code = "ma"),
            Country(name = "Mexico", code = "mx"),
            Country(name = "Malaysia", code = "my"),
            Country(name = "Nigeria", code = "ng"),
            Country(name = "Netherlands", code = "nl"),
            Country(name = "Norway", code = "no"),
            Country(name = "New Zealand", code = "nz"),
            Country(name = "Philippines", code = "ph"),
            Country(name = "Poland", code = "pl"),
            Country(name = "Portugal", code = "pt"),
            Country(name = "Romania", code = "ro"),
            Country(name = "Russian Federation", code = "ru"),
            Country(name = "Serbia", code = "rs"),
            Country(name = "South Africa", code = "za"),
            Country(name = "South Korea", code = "kr"),
            Country(name = "Sweden", code = "se"),
            Country(name = "Singapore", code = "sg"),
            Country(name = "Slovenia", code = "si"),
            Country(name = "Slovakia", code = "sk"),
            Country(name = "Switzerland", code = "ch"),
            Country(name = "Thailand", code = "th"),
            Country(name = "Turkey", code = "tr"),
            Country(name = "Taiwan", code = "tw"),
            Country(name = "United Arab Emirates", code = "ae"),
            Country(name = "United Kingdom", code = "gb"),
            Country(name = "United States Of America", code = "us"),
            Country(name = "Ukraine", code = "ua"),
            Country(name = "Venezuela", code = "ve")
        )
    }
}